[package]
name = "async-dispatcher"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["full"] }
