[package]
name = "async-dispatch"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"

[dev-dependencies]
tokio = { version = "0.2.17", features = ["full"] }
